// This code automatically generated by TableCodeGen

using System;
using System.Collections.Generic;
using C2TPro;

public class DemoTable
{
	public class Row
	{
		public string Year;
		public string Make;
		public string Model;
		public string Description;
		public float Price;

	}

	 List<Row> rowList = new List<Row>();
	 bool isLoaded;

	public  bool IsLoaded()
	{
		return isLoaded;
	}

	public  List<Row> GetRowList()
	{
        
		return rowList;
	}

	public  void Load(string csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser.Parse(csv);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Year = grid[i][0];
			row.Make = grid[i][1];
			row.Model = grid[i][2];
			row.Description = grid[i][3];
			row.Price = string.IsNullOrEmpty(grid[i][4]) ? 0 : Convert.ToSingle(grid[i][4]);

			rowList.Add(row);
		}
		isLoaded = true;
	}



	public  int NumRows()
	{
        
		return rowList.Count;
	}

	public  Row GetAt(int i)
	{
        
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public  Row Find_Year(string find)
	{
        
		return rowList.Find(x => x.Year == find);
	}
	public  List<Row> FindAll_Year(string find)
	{
        
		return rowList.FindAll(x => x.Year == find);
	}
	public  Row Find_Make(string find)
	{
        
		return rowList.Find(x => x.Make == find);
	}
	public  List<Row> FindAll_Make(string find)
	{
        
		return rowList.FindAll(x => x.Make == find);
	}
	public  Row Find_Model(string find)
	{
        
		return rowList.Find(x => x.Model == find);
	}
	public  List<Row> FindAll_Model(string find)
	{
        
		return rowList.FindAll(x => x.Model == find);
	}
	public  Row Find_Description(string find)
	{
        
		return rowList.Find(x => x.Description == find);
	}
	public  List<Row> FindAll_Description(string find)
	{
        
		return rowList.FindAll(x => x.Description == find);
	}
	public  Row Find_Price(float find)
	{
        
		return rowList.Find(x => x.Price == find);
	}
	public  List<Row> FindAll_Price(float find)
	{
        
		return rowList.FindAll(x => x.Price == find);
	}

}