{
    "showSculptingGridPlane": false,
    "raycastOntoFlatPlane": false,
    "showSceneViewInformation": true,
    "displaySceneViewSculptOntoMode": true,
    "displaySceneViewCurrentTool": true,
    "displaySceneViewCurrentHeight": true,
    "brushPreviewSize": 48,
    "texurePreviewSize": 64,
    "alwaysShowBrushSelection": false,
    "alwaysUpdateTerrainLODs": true,
    "invertBrushTexturesGlobally": false,
    "brushSelectionDisplayType": 2,
    "fauxModeSettings": [
        {
            "tool": 0,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 337.0,
                "brushSpeed": 2.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        },
        {
            "tool": 1,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 35.0,
                "brushSpeed": 1.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        },
        {
            "tool": 2,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 161.0,
                "brushSpeed": 2.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        },
        {
            "tool": 3,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 203.0,
                "brushSpeed": 2.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        },
        {
            "tool": 4,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 35.0,
                "brushSpeed": 1.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        },
        {
            "tool": 5,
            "settings": {
                "useFalloffForCustomBrushes": false,
                "invertFalloff": false,
                "selectedBrushTab": "All",
                "selectedBrushId": "_DefaultFalloffBrushName",
                "brushSize": 388.0,
                "brushSpeed": 1.0,
                "brushRoundness": 1.0,
                "brushAngle": 0.0,
                "useBrushSpacing": false,
                "minBrushSpacing": 1.0,
                "maxBrushSpacing": 30.0,
                "useRandomRotation": false,
                "minRandomRotation": -180.0,
                "maxRandomRotation": 180.0,
                "useRandomOffset": false,
                "randomOffset": 30.0,
                "invertBrushTexture": false
            }
        }
    ],
    "perlinNoiseScale": 20.0,
    "perlinNoiseMin": 0.0,
    "perlinNoiseMax": 1.0,
    "generateRampCurveInXAxis": true,
    "generateHeight": 5.0,
    "flattenMode": 1,
    "setHeight": 10.0,
    "boxFilterSize": 4,
    "smoothingIterations": 1,
    "mouldToolRaycastOffset": 0.014999999664723874,
    "mouldToolRaycastTopDown": false,
    "mouldToolBoxFilterSize": 5,
    "mouldAllIterations": 3,
    "mainDirectory": "Assets/Plugins/ArtPlugins/TerrainFormer/"
}